<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNuGJF61\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNuGJF61/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNuGJF61.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNuGJF61\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNuGJF61\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'NuGJF61',
    'container.build_id' => 'c90042cf',
    'container.build_time' => 1569845088,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNuGJF61');
