version: '3'
services:
    apache:
        build: .docker/apache
        container_name: apache
        ports:
          - 80:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - ./sf4:/home/wwwroot/sf4
        depends_on:
          - php

    mysql:
        image: mysql:latest
        container_name: mysql
        # volumes:
        #     - .docker/data/db:/var/lib/mysql
        # command: "tail -F anything"
            # - "--default-authentication-plugin=mysql_native_password"
            # - "--lower_case_table_names=1"
            # - "--character-set-server=utf8"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: docker-symfony-4
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        ports:
            - 3306:3306
            - 33060:33060

    db:
        image: mysql:5.7
        container_name: mysql57
        command: --default-authentication-plugin=mysql_native_password tail -F anything
        environment:
            MYSQL_DATABASE: test
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_RANDOM_ROOT_PASSWORD: root
        # volumes:
        #     - .docker/data:/var/lib/mysql
        ports:
            - 3300:3306

    php:
        build: .docker/php
        container_name: php
        volumes:
          - ./sf4:/home/wwwroot/sf4
        user: 1000:1000
        environment:
          - maildev_host=maildev
        depends_on:
          - maildev
          - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8080:80
        links:
            - mysql

    phpmyadmin2:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin2
        restart: always
        environment:
          PMA_HOST: mysql57
          PMA_PORT: 3306
        ports:
            - 8086:80
        
    maildev:
        image: djfarrelly/maildev
        container_name: maildev
        ports:
          - 8001:80
