version: '3'
services:
    apache:
        build: .docker/apache
        container_name: apache
        ports:
          - 80:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - ./sf4:/home/wwwroot/sf4
        depends_on:
          - php
        links: 
          - mysql:mysql

    mysql:
        container_name: mysql
        image: mysql/mysql-server
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sf4
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        user: "1000:1000"
        command:
            - "--default-authentication-plugin=mysql_native_password"
            - "--lower_case_table_names=1"
            - "--character-set-server=utf8"
        volumes:
            - ./.docker/data/db:/var/lib/mysql
        ports:
            - 3306:3306
            - 33060:33060
            
    php:
        build: .docker/php
        container_name: php
        volumes:
          - ./sf4:/home/wwwroot/sf4
        user: 1000:1000
        environment:
          - maildev_host=maildev
        depends_on:
          - maildev
          - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8080:80
        depends_on:
            - mysql
        
    maildev:
        image: djfarrelly/maildev
        container_name: maildev
        ports:
          - 8001:80



