<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKPacrhA\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKPacrhA/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKPacrhA.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKPacrhA\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKPacrhA\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KPacrhA',
    'container.build_id' => '23b8744e',
    'container.build_time' => 1569846135,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKPacrhA');
