<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUYAZiBa\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUYAZiBa/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUYAZiBa.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUYAZiBa\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUYAZiBa\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UYAZiBa',
    'container.build_id' => '1dab96fb',
    'container.build_time' => 1569852190,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUYAZiBa');
